onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - msw
  - sharp
  - unrs-resolver

patchedDependencies:
  '@laststance/redux-storage-middleware@0.2.0': patches/@laststance__redux-storage-middleware@0.2.0.patch
