import { configureStore } from '@reduxjs/toolkit'
import { act, render, screen, waitFor } from '@testing-library/react'
import { Provider } from 'react-redux'
import { beforeEach, describe, expect, test, vi } from 'vitest'

import { AddRepositoryCombobox } from '@/components/Board/AddRepositoryCombobox'
import { getAuthenticatedRepositoryCatalog } from '@/lib/actions/github'
import boardReducer from '@/lib/redux/slices/boardSlice'
import settingsReducer, {
  setOrganizationFilter,
} from '@/lib/redux/slices/settingsSlice'
import { toBoardId, toStatusListId } from '@/lib/types/brands'
import { handleGitHubTokenMissing } from '@/lib/utils/handle-github-token-missing'

vi.mock('@/lib/actions/github', () => ({
  getAuthenticatedRepositoryCatalog: vi.fn(),
}))

// The picker fetches repo placements on every opening; these tests are about
// the GitHub catalog, so placements resolve immediately with nothing placed.
vi.mock('@/lib/actions/board-data', () => ({
  getUserRepoPlacements: vi.fn(async () => ({
    success: true,
    data: { boards: [], maintenance: [] },
  })),
}))

vi.mock('@/lib/actions/repo-cards', () => ({
  addRepositoriesToBoard: vi.fn(),
}))

vi.mock('@/lib/utils/handle-github-token-missing', () => ({
  clearGitHubRefreshAttempts: vi.fn(),
  handleGitHubTokenMissing: vi.fn(),
}))

describe('AddRepositoryCombobox authentication recovery', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    window.history.replaceState({}, '', '/board/board-1')
  })

  // Generated by /ship coverage audit.
  // Value: protects=persisted filter labels and unavailable controls while loading;
  // fails_when=loading hides the label or permits organization selection;
  // why_new=existing component tests render a stand-in and hook tests cannot inspect the select; seam=none
  test.each([
    ['all', 'All Organizations', 'All Organizations'],
    ['laststance', 'laststance', 'laststance'],
    ['octocat', 'octocat', 'octocat (Personal)'],
  ])(
    'keeps the %s filter readable until GitHub options load, then enables selection',
    async (filter, pendingLabel, readyLabel) => {
      // Arrange
      const catalogRequest =
        Promise.withResolvers<
          Awaited<ReturnType<typeof getAuthenticatedRepositoryCatalog>>
        >()
      vi.mocked(getAuthenticatedRepositoryCatalog).mockReturnValue(
        catalogRequest.promise,
      )
      const store = configureStore({
        reducer: { board: boardReducer, settings: settingsReducer },
      })
      store.dispatch(setOrganizationFilter(filter))

      // Act
      render(
        <Provider store={store}>
          <AddRepositoryCombobox
            boardId={toBoardId('board-1')}
            statusId={toStatusListId('status-2')}
            isOpen
            onRepositoriesAdded={vi.fn()}
          />
        </Provider>,
      )

      // Assert
      const organizationFilter = screen.getByRole('combobox', {
        name: 'Organization filter',
      })
      expect(organizationFilter).toBeVisible()
      expect(organizationFilter).toHaveTextContent(pendingLabel)
      expect(organizationFilter).toBeDisabled()
      expect(screen.getByRole('status')).toHaveTextContent(
        'Loading repositories...',
      )

      // Act
      await act(async () => {
        catalogRequest.resolve({
          success: true,
          data: {
            currentUser: {
              id: 1,
              login: 'octocat',
              avatar_url: '',
              name: 'Octocat',
              type: 'User',
            },
            organizations: [
              { id: 2, login: 'laststance', avatar_url: '', description: '' },
            ],
            repositories: [],
          },
        })
      })

      // Assert
      expect(organizationFilter).toBeEnabled()
      expect(organizationFilter).toHaveTextContent(readyLabel)
      expect(screen.queryByRole('status')).toBeNull()
      expect(store.getState().settings.organizationFilter).toBe(filter)
    },
  )

  // Generated by /ship coverage audit.
  // Value: protects=the actual picker forwards its selected column into reauthentication;
  // fails_when=the component omits statusId or clears loading before navigation;
  // why_new=hook tests supply statusId directly and cannot catch missing component wiring; seam=none
  test('keeps the selected column and loading UI when the picker requires GitHub reauthentication', async () => {
    // Arrange
    window.history.replaceState({}, '', '/board/board-1?view=compact#cards')
    vi.mocked(getAuthenticatedRepositoryCatalog).mockResolvedValue({
      success: false,
      error: 'GitHub token not found. Please sign in again.',
      errorCode: 'GITHUB_TOKEN_MISSING',
    })
    vi.mocked(handleGitHubTokenMissing).mockReturnValue(true)
    const store = configureStore({
      reducer: { board: boardReducer, settings: settingsReducer },
    })

    // Act
    render(
      <Provider store={store}>
        <AddRepositoryCombobox
          boardId={toBoardId('board-1')}
          statusId={toStatusListId('status-2')}
          isOpen
          onRepositoriesAdded={vi.fn()}
        />
      </Provider>,
    )

    // Assert
    await waitFor(() => {
      expect(handleGitHubTokenMissing).toHaveBeenCalledWith(
        '/board/board-1?view=compact&addRepositoryTo=status-2#cards',
      )
    })
    expect(screen.getByRole('status')).toBeVisible()
    expect(screen.getByRole('status')).toHaveTextContent(
      'Loading repositories...',
    )
    expect(screen.queryByRole('alert')).toBeNull()
    expect(
      screen.getByRole('combobox', { name: 'Organization filter' }),
    ).toBeDisabled()
  })
})
