-- Temporary: Disable RLS for E2E testing
-- TODO: Re-enable RLS and add proper authentication setup for E2E tests

-- Disable RLS on all tables
ALTER TABLE Board DISABLE ROW LEVEL SECURITY;
ALTER TABLE StatusList DISABLE ROW LEVEL SECURITY;
ALTER TABLE RepoCard DISABLE ROW LEVEL SECURITY;
ALTER TABLE ProjectInfo DISABLE ROW LEVEL SECURITY;
ALTER TABLE Credential DISABLE ROW LEVEL SECURITY;
ALTER TABLE Maintenance DISABLE ROW LEVEL SECURITY;
ALTER TABLE AuditLog DISABLE ROW LEVEL SECURITY;
